kind: common.Repository
spec:
  conformLicenseCheck: false
  licenses:
    - enabled: false
  licenseChecks: []
---
kind: golang.Generate
spec:
  baseSpecPath: /testservice
  specs:
    - source: testservice/api/test.proto
